# Generated by Django 5.2.5 on 2025-08-26 01:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_squashed_0002_set_uuid_autoincrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(verbose_name='Produto')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Produto favorito',
                'verbose_name_plural': 'Produtos favoritos',
                'db_table': 'favorite_products',
            },
        ),
    ]
