# Generated by Django 5.2.5 on 2025-08-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_squashed_0002_set_uuid_autoincrement'),
        ('favorites', '0001_create_model_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproducts',
            unique_together={('client', 'product_id')},
        ),
    ]
